sonar.projectKey=eticketing-frontend-react
sonar.sources=src
sonar.exclusions=src/*.test.js,src/setupTests.js,src/reportWebVitals.js
sonar.tests=src
sonar.test.inclusions=src/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info